server:
  port: 9004

spring:
  profiles: dev
  servlet:
    multipart:
      max-file-size: 200MB #单个文件上传大小
      max-request-size: 600MB #连续上传文件大小
  application:
    name: Daemon
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.246.148:3306/zerotrust?characterEncoding=utf8
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.ustb.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/ustb/zerotrust/mapper/xml/*.xml # xml所在路径
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
logging:
  level:
    com.ustb: debug