server:
  port: 9002
spring:
  application:
    name: auth-resource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authority
    username: root
    password: 199748
  redis:
    host: localhost
    port: 6379
mybatis:
  type-aliases-package: com.ustb.zerotrust.domain
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ustb: debug
ustb:
  key:
    publicKeyPath: D:\\temp\\auth_key.pub