server:
  port: 8081
spring:
  profiles: prod
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.179.89:3306/zerotrust?characterEncoding=utf8
    username: root
    password: kingsoft


eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://192.168.179.91:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
logging:
  level:
    com.ustb: debug

feign:
  client:
    config:
      default:
        connectTimeout: 1000000  #单位毫秒
        readTimeout: 1000000