server:
  port: 8081
spring:
  application:
    name: auth-server


eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
logging:
  level:
    com.ustb: debug

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000