server:
  port: 8081
spring:
  profiles: dev
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.102.37.27:3306/zerotrust?characterEncoding=utf8
    username: root
    password: 123456


eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
logging:
  level:
    com.ustb: debug

feign:
  client:
    config:
      default:
        connectTimeout: 200000  #单位毫秒
        readTimeout: 200000