server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
#      - id: auth-org-server
#        uri: lb://auth-org-server # lb代表从注册中心获取服务
#        predicates:
#        - Path=/auth-org-server/**
#        filters:
#        - RewritePath=/auth-org-server/(?<segment>.*), /$\{segment}
      - id: auth-resource
        uri: lb://auth-resource # lb代表从注册中心获取服务
        predicates:
        - Path=/auth-resource/**
        filters:
        - RewritePath=/auth-resource/(?<segment>.*), /$\{segment}
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.ustb: debug
#ustb:
#  key:
#    publicKeyPath: D:\\temp\\auth_key.pub