server:
  port: 8080
spring:
  profiles: dev
  application:

    name: gateway
  cloud:
    gateway:
      routes:
      - id: resource # 我们自定义的路由 ID，保持唯一
        uri: http://localhost:9002 # 目标服务地址
        predicates: # 路由条件，Predicate 接受一个输入参数，返回一个布尔值结果
          - Path=/docker-resource/**
        filters:
          - RewritePath=/docker-resource/(?<segment>.*), /$\{segment}
      - id: auth-resource
        uri: lb://auth-resource # lb代表从注册中心获取服务
        predicates:
        - Path=/auth-resource/**
        filters:
        - RewritePath=/auth-resource/(?<segment>.*), /$\{segment}
      - id: soft-test-center
        uri: lb://soft-test-center # lb代表从注册中心获取服务
        predicates:
          - Path=/soft-test-center/**
        filters:
          - RewritePath=/soft-test-center/(?<segment>.*), /$\{segment}
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 300000  #单位毫秒
        readTimeout: 300000
logging:
  level:
    com.ustb: debug
#ustb:
#  key:
#    publicKeyPath: D:\\temp\\auth_key.pub