server:
  port: 9003
spring:
  application:
    name: soft-test-center
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///security_authority
    username: root
    password: 199748
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 200MB #设置总上传文件的大小
      max-file-size: 200MB #设置单个文件最大长度

mybatis:
  type-aliases-package: com.ustb.domain
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/ustb/zerotrust/mapper/xml/*.xml # xml所在路径
eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true #使用ip注册
logging:
  level:
    com.ustb: debug
